apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: k8s-nginx
  namespace: k8s
spec:
  rules:
  - host: ui.ops.com
    http:
      paths:
      - backend:
          service:
            name: ruoyi-nginx
            port:
              number: 83
        path: /
        pathType: Prefix
  - host: rgw.ops.com
    http:
      paths:
      - backend:
          service:
            name: ruoyi-gateway
            port:
              number: 8081
        path: /
        pathType: Prefix
  - host: monitor.ops.com
    http:
      paths:
      - backend:
          service:
            name: ruoyi-visual-monitor
            port:
              number: 9100
        path: /
        pathType: Prefix
