FROM ruoyi-init AS builder

FROM  openjdk:8-jre-alpine

WORKDIR /app

COPY --from=builder /app/ruoyi-visual-monitor.jar /app/ruoyi-visual-monitor.jar

ENTRYPOINT ["java","-jar","ruoyi-visual-monitor.jar"]