FROM ruoyi-init AS builder

FROM  openjdk:8-jre-alpine
ENV SW_AGENT="-javaagent:/app/skywalking-agent.jar \
              -Dskywalking.agent.service_name=ruoyi-gateway \
              -Dskywalking.collector.backend_service=sk-skywalking-oap.os:11800"
ENV JAVA_OPTS="-Xms128m -Xmx256m"
ENV JARNAME="ruoyi-gateway.jar"
WORKDIR /app


COPY --from=builder /app/ruoyi-gateway.jar /app/ruoyi-gateway.jar
COPY --from=builder /app/skywalking-agent.jar /app/skywalking-agent.jar
#使用 shell 处理
ENTRYPOINT ["sh", "-c", "java $SW_AGENT $JAVA_OPTS -jar -Duser.timezone=GMT+8 /app/$JARNAME "]