apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-gateway
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app: {{ include "helm.fullname" . }}-gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app: {{ include "helm.fullname" . }}-gateway
