{{- if and .Values.gateway.metrics.enabled .Values.gateway.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: ""
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm.fullname" . }}
      app: {{ include "helm.fullname" . }}-gateway
{{- end }}
