{{- if and .Values.auth.metrics.enabled .Values.auth.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: ""
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "helm.fullname" . }}-auth
{{- end }}
