FROM ruoyi-init AS builder

FROM  openjdk:8-jre-alpine

WORKDIR /app

COPY --from=builder /app/ruoyi-modules-system.jar /app/ruoyi-modules-system.jar

ENTRYPOINT ["java","-jar","ruoyi-modules-system.jar"]