kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-default
spec:
  repo: https://github.com/jadiy/fluxdemo.git
  paths:
  - helm
  targets:
  - clusterSelector:
      matchLabels:
        env: dev

