namespace: k8s
targetCustomizations:
  - name: dev
    helm:
      values:
        globalConfig:
          loadTest: false
        gateway:
          metrics:
            enabled: false
        auth:
          metrics:
            enabled: false
        modulesSystem:
          metrics:
            enabled: false
    clusterSelector:
      matchLabels:
        env: nomonitor
