namespace: k8s
targetCustomizations:
  - name: dev
    helm:
      values:
        gateway:
          metrics:
            enabled: false
    clusterSelector:
      matchLabels:
        env: dev
  - name: test
    helm:
      values:
        replicas: 3
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    helm:
      values:
        serviceType: LoadBalancer
        replicas: 3
    clusterSelector:
      matchLabels:
        env: prod
