# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
globalConfig:
  nacosHost: 192.168.11.14
  nacosPort: 8848
gateway:
  name: gateway
  image:
    repository: 192.168.11.14:5000/ruoyi-gateway
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: bfd43cc
  config:
    tracing: "-javaagent:/app/skywalking-agent.jar -Dskywalking.agent.service_name=ruoyi-gateway -Dskywalking.collector.backend_service=sw-skywalking-oap.os:11800"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
auth:
  name: auth
  image:
    repository: 192.168.11.14:5000/ruoyi-auth
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 47fc89f
  config:
    tracing: "-javaagent:/app/skywalking-agent.jar -Dskywalking.agent.service_name=ruoyi-auth -Dskywalking.collector.backend_service=sw-skywalking-oap.os:11800"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
modulesSystem:
  name: modules-system
  image:
    repository: 192.168.11.14:5000/ruoyi-modules-system
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: b70a1f5
  config:
    tracing: "-javaagent:/app/skywalking-agent.jar -Dskywalking.agent.service_name=ruoyi-modules-system -Dskywalking.collector.backend_service=sw-skywalking-oap.os:11800"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
