apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ruoyi-auth
  name: ruoyi-auth
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 8080
  selector:
    io.kompose.service: ruoyi-auth
status:
  loadBalancer: {}
