apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ruoyi-auth
  name: ruoyi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ruoyi-auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ruoyi-auth
    spec:
      containers:
      - env:
        - name: JARNAME
          value: ruoyi-auth.jar
        - name: auth-port
          value: "8080"
        - name: nacos-group
          value: DEFAULT
        - name: nacos-host
          value: 192.168.11.14
        - name: nacos-port
          value: "8848"
        image: kinshy-docker.pkg.coding.net/south/cross/docker_ruoyi-auth
        imagePullPolicy: ""
        name: ruoyi-auth
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
