apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ruoyi-gateway
  name: ruoyi-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ruoyi-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ruoyi-gateway
    spec:
      containers:
      - env:
        - name: JARNAME
          value: ruoyi-gateway.jar
        - name: gateway-port
          value: "8080"
        - name: nacos-group
          value: DEFAULT
        - name: nacos-host
          value: 192.168.11.14
        - name: nacos-port
          value: "8848"
        - name: sentinel-host
          value: 192.168.11.14
        - name: sentinel-port
          value: "8718"
        image: 192.168.11.14:5000/pipe:dev.2
        imagePullPolicy: ""
        name: ruoyi-gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
