apiVersion: v1
kind: Service
metadata:
  name: ruoyi-modules-system-dev
  namespace: k8s
  labels:
    app: ruoyi-modules-system-dev
spec:
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: ruoyi-modules-system-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-modules-system-dev
  namespace: k8s
  labels:
    app: ruoyi-modules-system-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-modules-system-dev
  template:
    metadata:
      labels:
        app: ruoyi-modules-system-dev
        version: v1
        using: dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - normal
      containers:
        - name: code
          env:
            - name: JARNAME
              value: ruoyi-modules-system.jar
            - name: port
              value: "8080"
            - name: nacos-group
              value: DEFAULT
            - name: nacos-host
              value: 192.168.11.14
            - name: nacos-port
              value: "8848"
            - name: sentinel-host
              value: 192.168.11.14
            - name: sentinel-port
              value: "8718"
          image: "192.168.11.14:5000/ruoyi-modules-system:96c1c5a"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 2
