apiVersion: v1
kind: Service
metadata:
  name: ruoyi-nginx-dev
  namespace: k8s
  labels:
    app: ruoyi-nginx-dev
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: ruoyi-nginx-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-nginx-dev
  namespace: k8s
  labels:
    app: ruoyi-nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-nginx-dev
  template:
    metadata:
      labels:
        app: ruoyi-nginx-dev
        version: v1
        using: dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - normal
      containers:
        - name: code
          env:
            - name: JARNAME
              value: ruoyi-nginx.jar
            - name: port
              value: "80"
            - name: nacos-group
              value: DEFAULT
            - name: nacos-host
              value: 192.168.11.14
            - name: nacos-port
              value: "8848"
            - name: sentinel-host
              value: 192.168.11.14
            - name: sentinel-port
              value: "8718"
          image: "192.168.11.14:5000/ruoyi-nginx:dev.8474c83"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 2
